# Generated by Django 5.2.6 on 2025-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(choices=[('05:00', '05:00 - 06:00'), ('06:00', '06:00 - 07:00'), ('07:00', '07:00 - 08:00'), ('08:00', '08:00 - 09:00'), ('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('12:00', '12:00 - 13:00'), ('16:00', '16:00 - 17:00'), ('17:00', '17:00 - 18:00'), ('18:00', '18:00 - 19:00'), ('19:00', '19:00 - 20:00'), ('20:00', '20:00 - 21:00')], default='05:00', max_length=5),
        ),
    ]
