# Generated by Django 4.2.14 on 2025-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_schedule_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_denied',
            field=models.BooleanField(default=False, help_text='Indica si se le negó el acceso por llegar después de la tolerancia'),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Hora exacta de llegada del cliente', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp exacto de cuando se canceló la reserva', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_arrival',
            field=models.BooleanField(default=False, help_text='Indica si el cliente llegó tarde a la clase'),
        ),
        migrations.AddField(
            model_name='membership',
            name='booking_priority',
            field=models.PositiveIntegerField(default=0, help_text='Prioridad de reserva: 0=normal, 1=alta prioridad (Elite, Power)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_duration_minutes',
            field=models.PositiveIntegerField(default=50, help_text='Duración real de la clase en minutos'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='late_tolerance_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Tolerancia para llegada tardía en minutos'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Tiempo de preparación/descanso en minutos'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('debit_card', 'Tarjeta Débito'), ('credit_card', 'Tarjeta Crédito'), ('visa_installments', 'Visa Cuotas'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='cash', help_text='Método de pago utilizado', max_length=20),
        ),
    ]
