# Generated by Django 4.2.14 on 2025-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_booking_access_denied_booking_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='access_denied',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_timestamp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='late_arrival',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='booking_priority',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='class_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='late_tolerance_minutes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='preparation_time_minutes',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(choices=[('05:00', '05:00 - 06:00'), ('06:00', '06:00 - 07:00'), ('07:00', '07:00 - 08:00'), ('08:00', '08:00 - 09:00'), ('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('12:00', '12:00 - 13:00'), ('16:00', '16:00 - 17:00'), ('17:00', '17:00 - 18:00'), ('18:00', '18:00 - 19:00'), ('19:00', '19:00 - 20:00')], default='05:00', max_length=5),
        ),
    ]
