# Generated by Django 4.2.14 on 2025-09-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_booking_access_denied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month_year',
            field=models.CharField(blank=True, help_text='Mes y año del recibo (formato: YYYY-MM)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Número único del recibo', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Fecha de inicio de vigencia del recibo', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Fecha de fin de vigencia del recibo', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(help_text='Hora de inicio (ej: 16:30)', max_length=5),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Hora de inicio (ej: 16:30)')),
                ('end_time', models.TimeField(help_text='Hora de fin (ej: 17:30)')),
                ('is_active', models.BooleanField(default=True, help_text='Horario activo/inactivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(help_text='Sede a la que pertenece este horario', on_delete=django.db.models.deletion.CASCADE, to='studio.sede')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['start_time'],
                'unique_together': {('sede', 'start_time', 'end_time')},
            },
        ),
    ]
