# Generated by Django 5.2.6 on 2025-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_payment_month_year_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Fecha efectiva de inicio de la membresía', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Fecha efectiva de fin de la membresía', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_advance_payment',
            field=models.BooleanField(default=False, help_text='Indica si es un pago anticipado para un mes futuro'),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_month',
            field=models.CharField(blank=True, help_text='Mes objetivo para pago anticipado (formato: YYYY-MM)', max_length=7, null=True),
        ),
    ]
