# Generated by Django 4.2.14 on 2025-09-11 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_membership',
            field=models.ForeignKey(blank=True, help_text='Membresía asignada manualmente al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.membership'),
        ),
        migrations.AddField(
            model_name='client',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede principal del cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.sede'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede asignada al usuario (solo para secretarias y coaches)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.sede'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('dpi__isnull', True), _negated=True), fields=('dpi',), name='unique_dpi_not_null'),
        ),
    ]
