# Generated by Django 4.2.14 on 2025-09-28 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_client_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indica si se ha enviado el correo con credenciales'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_login',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha iniciado sesión por primera vez'),
        ),
        migrations.AddField(
            model_name='client',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ha aceptado los términos y condiciones'),
        ),
        migrations.AddField(
            model_name='client',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando el cliente aceptó los términos y condiciones', null=True),
        ),
        migrations.CreateModel(
            name='TermsAcceptanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador/dispositivo', null=True)),
                ('client_first_name', models.CharField(default='', help_text='Nombre del cliente al momento de aceptación', max_length=100)),
                ('client_last_name', models.CharField(default='', help_text='Apellido del cliente al momento de aceptación', max_length=100)),
                ('client_dpi', models.CharField(blank=True, help_text='DPI del cliente al momento de aceptación', max_length=15, null=True)),
                ('client_email', models.EmailField(blank=True, help_text='Email del cliente al momento de aceptación', max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, help_text='Teléfono del cliente al momento de aceptación', max_length=15, null=True)),
                ('client_status', models.CharField(default='I', help_text='Estado del cliente al momento de aceptación', max_length=1)),
                ('client_created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del cliente al momento de aceptación')),
                ('user_username', models.CharField(default='', help_text='Username del usuario al momento de aceptación', max_length=150)),
                ('user_email', models.EmailField(blank=True, help_text='Email del usuario al momento de aceptación', max_length=254, null=True)),
                ('user_is_active', models.BooleanField(default=True, help_text='Estado activo del usuario al momento de aceptación')),
                ('user_date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro del usuario al momento de aceptación')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora exacta de aceptación')),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión del navegador', max_length=255, null=True)),
                ('referrer_url', models.URLField(blank=True, help_text='URL desde donde se aceptaron los términos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente que aceptó los términos', on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance_logs', to='accounts.client')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario autenticado que realizó la aceptación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Aceptación de Términos',
                'verbose_name_plural': 'Logs de Aceptación de Términos',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['client', '-accepted_at'], name='accounts_te_client__50502a_idx'), models.Index(fields=['ip_address', '-accepted_at'], name='accounts_te_ip_addr_578a69_idx'), models.Index(fields=['accepted_at'], name='accounts_te_accepte_7fad38_idx')],
            },
        ),
    ]
